apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-sessions
  labels:
    app.kubernetes.io/name: django
spec:
  ttlSecondsAfterFinished: 100
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      startingDeadlineSeconds: 90
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django
        spec:
          containers:
          - name: django
            image: k8s-django:latest
            imagePullPolicy: Never
            envFrom:
              - configMapRef:
                  name: django-configmap
            command:
              - python
              - manage.py
              - clearsessions
          restartPolicy: OnFailure
